// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  var customLog, intoArray,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    slice = [].slice;

  intoArray = function(args) {
    if (args.length < 2) {
      if (typeof args[0] === 'string') {
        args = args.join('').replace(/^\s+|\s+$/g, '').replace(/\s+/g, ' ').split(' ');
      } else if ((typeof args[0] === 'object') && (args[0] instanceof Array)) {
        args = args[0];
      }
    }
    return args;
  };

  customLog = function(init) {
    var CUSTOM_LOG, Log, enact, fn, level, log, logInstance, prefix, prefixMsg;
    CUSTOM_LOG = 'custom-log: ';
    Log = (function() {
      function Log(level, prefix) {
        this.assert = bind(this.assert, this);
        this.enable = bind(this.enable, this);
        this.disable = bind(this.disable, this);
        var prop, value;
        this.enabled = true;
        this.level = level || 'log';
        this.prefix = prefix || '';
        this.log = (function(_this) {
          return function() {
            var message, ref;
            if (_this.enabled) {
              message = arguments;
              if (_this.prefix) {
                message = (ref = [_this.prefix]).concat.apply(ref, arguments);
              }
              return console.log.apply(console, message);
            }
          };
        })(this);
        for (prop in this) {
          value = this[prop];
          if ((this.hasOwnProperty(prop)) && (prop !== 'log')) {
            this.log[prop] = value;
          }
        }
      }

      Log.prototype.disable = function() {
        this.enabled = false;
        return console.log(CUSTOM_LOG + '.' + this.level + ' is disabled');
      };

      Log.prototype.enable = function() {
        this.enabled = true;
        return console.log(CUSTOM_LOG + '.' + this.level + ' is enabled');
      };

      Log.prototype.assert = function(predicate, description) {
        if (description == null) {
          description = '';
        }
        if (typeof predicate === 'string') {
          description = predicate;
        }
        if (description) {
          description = '(' + description + ') == ';
        }
        if (typeof predicate === 'string') {
          predicate = eval(predicate);
        }
        if (predicate) {
          predicate = 'TRUE';
        } else {
          predicate = 'FALSE';
        }
        return this.log('\n\t' + customLog.assertMessage + description + predicate + '\n');
      };

      return Log;

    })();
    if (typeof init === 'string') {
      prefixMsg = init;
    }
    logInstance = new Log('log', prefixMsg);
    log = logInstance.log;
    enact = function() {
      var i, len, level, levels, method, results;
      method = arguments[0], levels = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      levels = intoArray(levels);
      results = [];
      for (i = 0, len = levels.length; i < len; i++) {
        level = levels[i];
        if (level === 'log') {
          results.push(logInstance[method]());
        } else if (log[level] != null) {
          results.push(log[level][method]());
        } else {
          results.push(void 0);
        }
      }
      return results;
    };
    log.enable = function() {
      return enact.apply(null, ['enable'].concat(slice.call(arguments)));
    };
    log.disable = function() {
      return enact.apply(null, ['disable'].concat(slice.call(arguments)));
    };
    if (typeof init === 'object') {
      fn = function(level, prefix) {
        switch (level) {
          case 'log':
            return logInstance.prefix = prefix;
          case 'assert':
            return customLog.assertMessage = prefix;
          default:
            return log[level] = new Log(level, prefix).log;
        }
      };
      for (level in init) {
        prefix = init[level];
        fn(level, prefix);
      }
    }
    return log;
  };

  customLog.assertMessage = 'Assert: ';

  if ((typeof define !== "undefined" && define !== null) && ('function' === typeof define) && define.amd) {
    define('customLog', [], function() {
      return customLog;
    });
  } else if (typeof module !== 'undefined') {
    module.exports = customLog;
  } else if (typeof window !== 'undefined') {
    window.customLog = customLog;
  }

}).call(this);
